### ISSUE TITLE
Clean install (without MindMeld) fails to run, error during 'click' dependency import

### ISSUE THREAD

**Issue by dstaudt** [cisco/webex-assistant-sdk#61]
1. Create a fresh Python 3.7.13 venv: `python3 -m venv venv`
1. Install just webex-skills: `pip install webex-skills`
1. Pip freeze shows `click` 8.10 is installed
1. Run, e.g.: `webex-skills project init --help`
1. Stacktrace:
    ```
    Traceback (most recent call last):
    File "/Users/user/.pyenv/versions/3.7.5/envs/acronymbot/bin/webex-skills", line 6, in <module>
    from webex_skills.cli import main
    File "/Users/user/.pyenv/versions/3.7.5/envs/acronymbot/lib/python3.7/site-packages/webex_skills/cli/init.py", line 1, in <module>
    import typer
    File "/Users/user/.pyenv/versions/3.7.5/envs/acronymbot/lib/python3.7/site-packages/typer/init.py", line 12, in <module>
    from click.termui import get_terminal_size as get_terminal_size
    ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/Users/user/.pyenv/versions/3.7.5/envs/acronymbot/lib/python3.7/site-packages/click/[termui.py](https://termui.py/))
    ```
Seems to be related to `typer` issue: https://github.com/tiangolo/typer/issues/377

Note: going on to install `webex-skills[mindmeld]` results in `click` 8.1.0 being uninstalled and 7.1.2 reinstalled - avoiding the issue.

`webex-skills` should be able to work-around the problem by pinning `click` 7.1.2

**Comment by tiangolo** [comment]
I just released Typer `0.4.1` that should handle it. :rocket: :nerd_face:

**Comment by dstaudt** [comment]
Thanks, that fixed it for me for `pip install webex-skills`.
However, for `pip install webex-skills[mindmeld]` pip is reporting a couple of dependency errors during the install/build:
```
ERROR: flask 1.1.4 has requirement click<8.0,>=5.1, but you'll have click 8.1.1 which is incompatible.
ERROR: mindmeld 4.4.2 has requirement Click~=7.1, but you'll have click 8.1.1 which is incompatible.
```
Superficial testing seems to indicate everything is working OK regardless, but at least flask seems to be used for test.  Will open a separate issue...

**Comment by dstaudt** [comment]
FYI, updating pip to 22.0.4 can't reproduce the above.
